name: Update API

on:
  workflow_call:
  push:
    paths:
      - 'APIs/Petstore/petstore.yaml'

env:
  baseURL: 'https://analystsdemo.apigw-aw-eu.webmethods.io/rest/apigateway/'
  apiId: 'cb7fcbf0-fc21-46ef-8d55-936480d4997f'
  policyId: ''

jobs:
  update-api:
    runs-on: [ analysts-demo ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deactivate API
        run: |
          echo "Deactivating API"

      - name: Update API
        run: |
          echo "Update API"

      - name: Activate API
        run: |
          curl --location '${{ env.baseURL }}/apis/${{ env.apiId }}/activate' --header 'Accept: application/json' --header 'Authorization: Basic Z29rdWwucmFqOnFteS1rZHY1cXJ6IWJjZi5LWU4='
