name: Update API

on:
  workflow_dispatch:

  push:
    paths:
      - 'APIs/Petstore/petstore.yaml'
      - '.github/workflows/*'

env:
  baseURL: 'https://analystsdemo.apigw-aw-eu.webmethods.io/rest/apigateway/'
  apiId: 'cb7fcbf0-fc21-46ef-8d55-936480d4997f'
  policyId: ''

jobs:
  update-api:
    runs-on: [ analysts-demo ]
    steps:
      - name: Deactivate API
        run: |
          deactivate_status=$(curl -o /dev/null -s -w "%{http_code}" --location --request PUT "${{ vars.baseURL }}/apis/${{ vars.apiId }}/deactivate" -H "Accept: application/json" -H "Authorization: Basic ")
          
          if [ "${deactivate_status}" == "200" ]; then
            echo "API deactivated successfully."
          else
            echo "Unable to deactivate API."
            exit 1
          fi

      - name: Update API
        run: |
          echo "Update API"

      - name: Activate API
        run: |
          activate_status=$(curl -o /dev/null -s -w "%{http_code}" --location --request PUT "${{ vars.baseURL }}/apis/${{ vars.apiId }}/activate" -H "Accept: application/json" -H "Authorization: Basic Z29rdWwucmFqOnFteS1rZHY1cXJ6IWJjZi5LWU4=")
          
          if [ "${activate_status}" == "200" ]; then
            echo "API activated successfully."
          else
            echo "Unable to activate API."
            exit 1
          fi