name: Update API

on:
  workflow_call:
  push:
    paths:
      - 'APIs/Petstore/petstore.yaml'

jobs:
  update-api:
    runs-on: [ analysts-demo ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deactivate API
        run: |
          echo "Deactivating API"

      - name: Update API
        run: |
          echo "Update API"

      - name: Activate API
        run: |
          echo "Activate API"
